<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogosSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('catalogos')->insert([
            [
            'catalogo' => '2201001001',
            'descripcion' => 'Alim. Agua Purificada',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001002',
            'descripcion' => 'Alim. Reunión Corte Apelación, Suprema y Consejo Cord Zonal',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001003',
            'descripcion' => 'Alim. Reunión Comite Paritario',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001004',
            'descripcion' => 'Alim. Reunión Consejo de Bienestar',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001005',
            'descripcion' => 'Alim. Capacitación Comité Paritario',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001006',
            'descripcion' => 'Alim. Reunión Departamentos o Administraciones Zonales',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001007',
            'descripcion' => 'Alim. Compensatorio Oficial Asistente Ministro',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001008',
            'descripcion' => 'Alim. Otros',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2202001000',
            'descripcion' => 'Textiles y Acabados Textiles',
            'item' => 2202,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2202002000',
            'descripcion' => 'Vestuario, Accesorios y Prendas Diversas',
            'item' => 2202,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2202003000',
            'descripcion' => 'Calzado',
            'item' => 2202,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203001001',
            'descripcion' => 'Comb. Vehiculo Pdte. Supremo / Ministro / Fiscal / Director',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203001002',
            'descripcion' => 'Comb. Vehiculo Capj',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203001003',
            'descripcion' => 'Comb. Reembolso',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203001004',
            'descripcion' => 'Comb. Vehiculos Otros',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203002000',
            'descripcion' => 'Para Maquinarias, Equipos de Producción,Tracción y Elevación',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203003000',
            'descripcion' => 'Para Calefacción',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203999000',
            'descripcion' => 'Para Otros',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204001000',
            'descripcion' => 'Materiales de Oficina',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204002000',
            'descripcion' => 'Textos y Otros Materiales de Enseñanza',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204004000',
            'descripcion' => 'Productos Farmacéuticos',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204007000',
            'descripcion' => 'Materiales y Útiles de Aseo',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204008000',
            'descripcion' => 'Menaje para Oficina, Casino y Otros',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204009000',
            'descripcion' => 'Insumos, Repuestos y Accesorios Computacionales',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204010000',
            'descripcion' => 'Materiales para Mantenimiento y Reparaciones de Inmuebles',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204011000',
            'descripcion' => 'Repuestos y Accesorios para Manten. y Reparacion de Vehículo',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204012000',
            'descripcion' => 'Otros Materiales, Repuestos y Útiles Diversos para Mantenimi',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204013000',
            'descripcion' => 'Equipos Menores',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204014000',
            'descripcion' => 'Productos Elaborados de Cuero, Caucho y Plásticos',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204015000',
            'descripcion' => 'Productos Agropecuarios y Forestales',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204999001',
            'descripcion' => 'Certificados Digitales',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204999002',
            'descripcion' => 'Otros',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205001000',
            'descripcion' => 'Electricidad',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205002000',
            'descripcion' => 'Agua',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205003000',
            'descripcion' => 'Gas',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205004001',
            'descripcion' => 'Correo Normal',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205004002',
            'descripcion' => 'Correo Arriendo de Casilla',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205005000',
            'descripcion' => 'Telefonía Fija',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205006001',
            'descripcion' => 'Telefonía Celular Cuota Fija',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205006002',
            'descripcion' => 'Telefonía Celular Compra de Equipos Celulares',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205006003',
            'descripcion' => 'Telefonía Celular Recarga de Equipo Satelital',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205007000',
            'descripcion' => 'Acceso a Internet',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205008000',
            'descripcion' => 'Enlaces de Telecomunicaciones',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205999000',
            'descripcion' => 'Otros',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001001',
            'descripcion' => 'Cerrajería',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001002',
            'descripcion' => 'Gasfitería',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001003',
            'descripcion' => 'Otras Reparaciones - Edificaciones',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001004',
            'descripcion' => 'Mant. y Rep. Camaras Alcantarillado - Sanitarias',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001005',
            'descripcion' => 'Mant. y Rep. Ascensor',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001006',
            'descripcion' => 'Mant. y Rep. de Estanques',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001007',
            'descripcion' => 'Mant. y Rep. Módulos Fotovoltaicos',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001008',
            'descripcion' => 'Mant. y Rep. Salvaescalera',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001009',
            'descripcion' => 'Mant. y Rep. Tablero Eléctrico',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001010',
            'descripcion' => 'Mant. y Rep. Techumbre / Canaleta',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001011',
            'descripcion' => 'Mant. Y Rep. Red Húmeda y seca',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001012',
            'descripcion' => 'Mant. y Rep. Sist. Eléctrico / Iluminación',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001013',
            'descripcion' => 'Mant. y Rep. Aire Acondicionado',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001014',
            'descripcion' => 'Mant. y Rep. Sistema de Calefacción',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001015',
            'descripcion' => 'Mant. y Rep. Calderas',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001016',
            'descripcion' => 'Mant. y Rep. Bombas de Elevación de Agua',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001017',
            'descripcion' => 'Mant. y Rep. Grupo Electrógeno',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001018',
            'descripcion' => 'Mant. Y Rep. Control Acceso',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001020',
            'descripcion' => 'Obras de Habilitaciones',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001021',
            'descripcion' => 'Pinturas Edificaciones',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206002000',
            'descripcion' => 'Mantenimiento y Reparación de Vehículos',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206003000',
            'descripcion' => 'Mantenimiento y Reparación de Mobiliarios y Otros',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004001',
            'descripcion' => 'Mant. y Rep. Portón Eléctrico',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004002',
            'descripcion' => 'Mant. y Rep. Central Telefónica',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004003',
            'descripcion' => 'Mant. y Rep. Equipos Audio',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004005',
            'descripcion' => 'Mant. y Rep. Detector de Metales / Rayos X',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004006',
            'descripcion' => 'Mant. y Rep. Sistema Detección de Incendio',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004007',
            'descripcion' => 'Mant. y Rep. Alarmas',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004008',
            'descripcion' => 'Mant. y Rep. CCTV',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004009',
            'descripcion' => 'Mant. y Recarga Extintores',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004010',
            'descripcion' => 'Otras Reparaciones Menores de Maq. y Eq. de Oficina',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206006000',
            'descripcion' => 'Mantenimiento y Reparación de Otras Maquinarias y Equipos',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007001',
            'descripcion' => 'Mant. y Rep. Sistemas Computacionales',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007002',
            'descripcion' => 'Mant. y Rep. Tottem',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007003',
            'descripcion' => 'Mant. y Rep. Fotocopiadora',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007004',
            'descripcion' => 'Mant. y Rep. Escáner Computacionales',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007005',
            'descripcion' => 'Mant. y Rep. Tarjetas de Accesos',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007006',
            'descripcion' => 'Mant. y Rep. Impresoras, Multifuncionales y Ploter',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007007',
            'descripcion' => 'Mant. y Rep. Puntos de Red, de Voz y Datos',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007008',
            'descripcion' => 'Mant. y Rep. UPS',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007009',
            'descripcion' => 'Mant. y Rep. PC',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007010',
            'descripcion' => 'Otras Rep. Equipos Informáticos',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206999000',
            'descripcion' => 'Otros',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207001001',
            'descripcion' => 'Servicios de Publicidad Televisiva y Audiovisual',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207001002',
            'descripcion' => 'Servicios de Publicidad Radial',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207001003',
            'descripcion' => 'Servicios de Publicidad Medios Escritos',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207001004',
            'descripcion' => 'Otros Servicios de Publicidad',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207002000',
            'descripcion' => 'Servicios de Impresión',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207003000',
            'descripcion' => 'Servicios de Encuadernación y Empaste',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207999000',
            'descripcion' => 'Otros',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208001001',
            'descripcion' => 'Servicio de Aseo Dependencias',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208001002',
            'descripcion' => 'Servicio de Fumigación y Sanitización',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208001003',
            'descripcion' => 'Servicio Retiro Residuos, Basura, Escombros, Poda y Desmalez',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208001004',
            'descripcion' => 'Otros Aseo',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208002001',
            'descripcion' => 'Servicio de Guardias de Seguridad',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208002002',
            'descripcion' => 'Servicio de Alarmas y Monitoreo',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208002003',
            'descripcion' => 'Otros Vigilancia',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208003000',
            'descripcion' => 'Servicios de Mantención de Jardines',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007001',
            'descripcion' => 'Pasajes y Movilización Normales Terrestres',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007002',
            'descripcion' => 'Pasajes y Movilización Curs. Acad. Jud',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007003',
            'descripcion' => 'Pasajes y Movilización por Notificaciones',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007004',
            'descripcion' => 'Traslado de Valijas, Courier y Expedientes',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007005',
            'descripcion' => 'Permiso de Circulación y Patente',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007006',
            'descripcion' => 'Traslado por Nombramiento',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007007',
            'descripcion' => 'Otros Pasajes, Fletes y Bodegajes',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007008',
            'descripcion' => 'Pasajes y Movilización Normales Aéreos',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208008000',
            'descripcion' => 'Salas Cunas y/o Jardines Infantiles',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208010000',
            'descripcion' => 'Servicios de Suscripción y Similares',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208999001',
            'descripcion' => 'Servicio de Coffe Break, Cocteleria y Banqueteria',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208999002',
            'descripcion' => 'Servicio Suministro e Instalación de Señaletica (Letrero)',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208999003',
            'descripcion' => 'Servicio para Plan de Difusion y Comunicación',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208999004',
            'descripcion' => 'Servicio para Apoyo Digitalizacion',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208999005',
            'descripcion' => 'Servicio De Aromatización y/o Odorización',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208999006',
            'descripcion' => 'Otros Servicios Generales',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209001000',
            'descripcion' => 'Arriendo de Terrenos',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209002001',
            'descripcion' => 'Arriendo de Inmuebles',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209002002',
            'descripcion' => 'Gasto Común Edificio Arrendado',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209002003',
            'descripcion' => 'Arriendos de Bodega',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209002004',
            'descripcion' => 'Arriendos de Estacionamientos',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209002005',
            'descripcion' => 'Otros Arriendos Edificios',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209003000',
            'descripcion' => 'Arriendo de Vehículos',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209004000',
            'descripcion' => 'Arriendo de Mobiliario y Otros',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209005000',
            'descripcion' => 'Arriendo de Máquinas y Equipos',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209006000',
            'descripcion' => 'Arriendo de Equipos Informáticos',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209999000',
            'descripcion' => 'Otros',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2210002001',
            'descripcion' => 'Seguro Vehículos',
            'item' => 2210,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2210002002',
            'descripcion' => 'Seguro Inmuebles',
            'item' => 2210,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2210002003',
            'descripcion' => 'Otros Seguros',
            'item' => 2210,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2210004000',
            'descripcion' => 'Gastos Bancarios',
            'item' => 2210,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2210999000',
            'descripcion' => 'Otros',
            'item' => 2210,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211001000',
            'descripcion' => 'Estudios e Investigaciones',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211002001',
            'descripcion' => 'Cursos de Capacitación CAPJ',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211002002',
            'descripcion' => 'Cursos de Capacitación Academia Judicial',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211002003',
            'descripcion' => 'Cursos de Capacitación Becas de Perfeccionamiento',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211002004',
            'descripcion' => 'Cursos de Capacitación Desarrollo Organizacional',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211003000',
            'descripcion' => 'Servicios Informáticos',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999001',
            'descripcion' => 'Servicio de Traducción y/o Interprete (Lengua)',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999002',
            'descripcion' => 'Servicio de Revisión Técnica de Vehículos',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999003',
            'descripcion' => 'Servicio de Conducción y/o Reemplazo Oficial Asistente (Chof',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999004',
            'descripcion' => 'Servicio de Mayordomía',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999005',
            'descripcion' => 'Servicio de Administración Técnica de Edificios',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999006',
            'descripcion' => 'Certificaciónes',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999007',
            'descripcion' => 'Gastos Comunes Edificio Propio',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999008',
            'descripcion' => 'Servicio de Cuidador',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999009',
            'descripcion' => 'Mecánica de Suelos, Levantamiento Topógráfico y Tasaciones',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999010',
            'descripcion' => 'Otros Servicios Profesionales',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2212002000',
            'descripcion' => 'Gastos Menores',
            'item' => 2212,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2212003000',
            'descripcion' => 'Gastos de Representación, Protocolo y Ceremonial',
            'item' => 2212,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2212004000',
            'descripcion' => 'Intereses, Multas y Recargos',
            'item' => 2212,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2212005000',
            'descripcion' => 'Derechos y Tasas',
            'item' => 2212,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2212999000',
            'descripcion' => 'Otros',
            'item' => 2212,
            'estado' => 'Activo',
        ]
        ]);
    }
}
