<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Contrato;

class ContratosSeeder extends Seeder
{
   
    public function run(): void
    {
        DB::table('contratos')->insert([
    [
            'contrato'=> '269', 
            'licitacion'=> '0', 
            'tipo'=> 'Arriendo', 
            'referencia'=> 'CONTRATO DE ARRENDAMIENTO PARA JUZGADO DE LETRAS DEL TRABAJO COYHAIQUE', 
            'fechainicio'=> '2004-12-01', 
            'fechavencimiento'=> '2025-12-31', 
            'razonsocial'=> 'SUCESIÓN ANTONIO VARONA HUIDOBRO', 
            'rut'=> '53241840-2', 
            'materia'=> 'MODULO ARRIENDOS', 
            'submateria'=> 'ARRIENDOS', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '285', 
            'licitacion'=> '0', 
            'tipo'=> 'Arriendo', 
            'referencia'=> 'Contrato de Arrendamiento del inmueble del Juzgado de Familia de Coyhaique  con INMOBILIARIA E INVERSIONES ANGIRO SpA', 
            'fechainicio'=> '2009-06-01', 
            'fechavencimiento'=> '2027-12-31', 
            'razonsocial'=> 'INMOBILIARIA E INVERSIONES ANGIRO SpA,', 
            'rut'=> '76524302-5', 
            'materia'=> 'MODULO ARRIENDOS', 
            'submateria'=> 'ARRIENDOS', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '1309', 
            'licitacion'=> 'PJ1309', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE MANTENIMIENTO DE SERVICIO BÁSICO DE ASCENSORES EDIFICIO ICA COYHAIQUE', 
            'fechainicio'=> '2008-01-02', 
            'fechavencimiento'=> '2030-12-31', 
            'razonsocial'=> 'THYSSENKRUPP ELEVADORES SA', 
            'rut'=> '96726480-6', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT ASCENSORES', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '1312', 
            'licitacion'=> 'PJ1312', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE MANTENCION DE JARDINES Y AREAS VERDES EDIFICIO JUZGADO DE LETRAS DEL TRABAJO', 
            'fechainicio'=> '2008-02-15', 
            'fechavencimiento'=> '2030-12-31', 
            'razonsocial'=> 'ALVARO JARA POBLETE', 
            'rut'=> '9781824-K', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'MANTENCIÓN DE JARDINES', 
            'estado'=> 'APROBADO' 
            ],
            [
                'contrato'=> '1313', 
            'licitacion'=> 'PJ1313', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE MANTENCION DE JARDINES Y AREAS VERDES DEL JUZGADO DE GARANTIA DE COYHAIQUE', 
            'fechainicio'=> '2005-01-01', 
            'fechavencimiento'=> '2030-12-31', 
            'razonsocial'=> 'ALVARO JARA POBLETE', 
            'rut'=> '9781824-K', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'MANTENCIÓN DE JARDINES', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '4564', 
            'licitacion'=> '0', 
            'tipo'=> 'Arriendo', 
            'referencia'=> 'Contrato de arrendamiento para el Primer Juzgado de Letras de Coyhaique con Sociedad Inmobiliaria Pangal Ltda\t', 
            'fechainicio'=> '2002-04-15', 
            'fechavencimiento'=> '2025-04-15', 
            'razonsocial'=> 'SOCIEDAD INMOBILIARIA PANGAL LTDA', 
            'rut'=> '79952920-3', 
            'materia'=> 'MODULO ARRIENDOS', 
            'submateria'=> 'ARRIENDOS', 
            'estado'=> 'APROBADO' 
         ],
            [
                'contrato'=> '16913', 
            'licitacion'=> '0', 
            'tipo'=> 'Arriendo', 
            'referencia'=> 'Contrato de Arrendamiento de inmueble para la Administración Zonal de Coyhaique', 
            'fechainicio'=> '2021-12-21', 
            'fechavencimiento'=> '2024-12-21', 
            'razonsocial'=> 'SADI DEL CARMEN AUAD NASER', 
            'rut'=> '8481744-9', 
            'materia'=> 'MODULO ARRIENDOS', 
            'submateria'=> 'ARRIENDOS', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '17827', 
            'licitacion'=> '2182-1-LE20', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'SERVICIO DE JARDINERÍA PARA LOCALIDADES DE COYHAIQUE', 
            'fechainicio'=> '2020-02-02', 
            'fechavencimiento'=> '2023-02-02', 
            'razonsocial'=> 'ARNALDO TOBAR RAMIREZ', 
            'rut'=> '13504547-0', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'MANTENCIÓN DE JARDINES', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '17828', 
            'licitacion'=> '2182-1-LE20', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'SERVICIO DE JARDINERIA PARA LOCALIDAD DE COCHRANE', 
            'fechainicio'=> '2020-02-03', 
            'fechavencimiento'=> '2023-02-03', 
            'razonsocial'=> 'JUAN ANDRES IRQUEN IRQUEN', 
            'rut'=> '15305910-1', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'MANTENCIÓN DE JARDINES', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '18387', 
            'licitacion'=> '2182-5-LE20', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'SERVICIO DE MANTENCION DE JARDINES DE EDIFICIO DEL JUZGADO DE LETRAS DE PUERTO CISNES', 
            'fechainicio'=> '2020-03-13', 
            'fechavencimiento'=> '2023-03-13', 
            'razonsocial'=> 'SANDRA SOLEDAD AGUILA ROSAS', 
            'rut'=> '9348839-3', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'MANTENCIÓN DE JARDINES', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '18388', 
            'licitacion'=> '2182-3-LE20', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'SERVICIO DE MANTENCION DE JARDINES DE EDIFICIO DEL JUZGADO DE LETRAS DE CHILE CHICO', 
            'fechainicio'=> '2020-03-16', 
            'fechavencimiento'=> '2023-03-16', 
            'razonsocial'=> 'CESAR ULISES MARDONES QUIROZ', 
            'rut'=> '10416953-8', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'MANTENCIÓN DE JARDINES', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '18407', 
            'licitacion'=> '2182-2-LE20', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE PRESTACIÓN DE SERVICIO DE MANTENCIÓN PREVENTIVA Y  CORRECTIVA DE CALDERAS DE CALEFACCIÓN DE TRIBUNALES DE LA JURISDICCIÓN DE AYSÉN', 
            'fechainicio'=> '2020-03-02', 
            'fechavencimiento'=> '2023-03-02', 
            'razonsocial'=> 'MARCIAL ROBERTO MORENO GATICA', 
            'rut'=> '12975530-K', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT CALDERAS', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '18426', 
            'licitacion'=> '741422-1-LE20', 
            'tipo'=> 'Convenio precio', 
            'referencia'=> 'CONVENIO DE USO PREFERENTE DE TRANSPORTE POR NOTIFICACIONES PARA EL JUZGADO DE FAMILIA DE COYHAIQUE', 
            'fechainicio'=> '2020-04-02', 
            'fechavencimiento'=> '2023-04-02', 
            'razonsocial'=> 'JULIA GLADYS MARTINEZ GARCIA', 
            'rut'=> '7672718-K', 
            'materia'=> 'SERVICIO DE TRANSPORTE', 
            'submateria'=> 'PASAJE DE MOVILIZACIÓN POR NOTIFICACIONES', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '18427', 
            'licitacion'=> '741488-1-LE20', 
            'tipo'=> 'Convenio precio', 
            'referencia'=> 'CONVENIO DE USO PREFERENTE DE TRANSPORTE POR NOTIFICACIONES PARA TRIBUNAL DE JUICIO ORAL EN LO PENAL DE COYHAIQUE', 
            'fechainicio'=> '2020-03-03', 
            'fechavencimiento'=> '2023-03-03', 
            'razonsocial'=> 'DELFIN OLIVARES JARA', 
            'rut'=> '7762264-0', 
            'materia'=> 'SERVICIO DE TRANSPORTE', 
            'submateria'=> 'PASAJE DE MOVILIZACIÓN POR NOTIFICACIONES', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '19236', 
            'licitacion'=> '2182-6-LE20', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE ALCANTARILLADO Y SSHH DE TRIBUNALES DE LA JURISDICCIÓN DE AYSEN', 
            'fechainicio'=> '2020-07-17', 
            'fechavencimiento'=> '2023-07-17', 
            'razonsocial'=> 'LUIS PATRICIO VALDÉS GUTIÉRREZ', 
            'rut'=> '9728223-4', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT DE CAMARAS ALCANTARILLADO', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '19336', 
            'licitacion'=> '2182-7-LE20', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE MANTENIMIENTO PREVENTIVO Y CORRECTIVO DE TABLEROS ELÉCTRICOS DE EDIFICIOS DE LA JURISDICCIÓN DE AYSEN', 
            'fechainicio'=> '2020-07-20', 
            'fechavencimiento'=> '2023-07-20', 
            'razonsocial'=> 'CONSTRUCTORA EHG LIMITADA', 
            'rut'=> '76499318-7', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT TABLERO ELECTRICO', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '19717', 
            'licitacion'=> '2182-10-LE20', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE PRESTACIÓN DE SERVICIO DE MANTENCION PREVENTIVA Y CORRECTIVA DE  GRUPOS ELECTROGENOS DE TRIBUNALES JURISDICCION DE AYSEN', 
            'fechainicio'=> '2020-08-02', 
            'fechavencimiento'=> '2023-08-02', 
            'razonsocial'=> 'CONSTRUCTORA EHG LIMITADA', 
            'rut'=> '76499318-7', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT GRUPO ELECTROGENO', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '19718', 
            'licitacion'=> '741256-2-LE20', 
            'tipo'=> 'Convenio precio', 
            'referencia'=> 'CONVENIO DE USO PREFERENTE DE TRANSPORTE POR NOTIFICACIONES PARA EL JUZGADO DE GARANTIA DE COYHAIQUE', 
            'fechainicio'=> '2020-08-04', 
            'fechavencimiento'=> '2023-08-04', 
            'razonsocial'=> 'ISMAEL ALFONSO GODOY ALVAREZ', 
            'rut'=> '14043093-5', 
            'materia'=> 'SERVICIO DE TRANSPORTE', 
            'submateria'=> 'PASAJE DE MOVILIZACIÓN POR NOTIFICACIONES', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '20041', 
            'licitacion'=> '2182-12-LE20', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'SERVICIO DE MANTENCIÓN Y REPARACIÓN  DE TECHUMBRES, VENTANAS Y CONVENIO DE PRECIOS DE OBRAS MENORES DE TRIBUNALES DE LA JURISDICCIÓN DE AYSEN', 
            'fechainicio'=> '2020-09-02', 
            'fechavencimiento'=> '2023-09-02', 
            'razonsocial'=> 'SAVIA DEL TRANSITO HUENTEO HERRERA', 
            'rut'=> '11717210-4', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT TECHUMBRE /CANALETA', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '21211', 
            'licitacion'=> 'PJ21211', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'MANTENCION DE JARDINES EN TRIBUNAL DE JUICIO ORAL EN LO PENAL COYHAIQUE', 
            'fechainicio'=> '2005-02-11', 
            'fechavencimiento'=> '2030-12-31', 
            'razonsocial'=> 'ALVARO JARA POBLETE', 
            'rut'=> '9781824-K', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'MANTENCIÓN DE JARDINES', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '21414', 
            'licitacion'=> '2182-1-LE21', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'SERVICIO DE MANTENCIÓN PREVENTIVA Y REPARATIVA DE SISTEMA DE CALEFACCION POR TERMO ACUMULADORES ELECTRICOS PARA TRIBUNALES DE LA JURISDICCION DE COYHAIQUE', 
            'fechainicio'=> '2021-04-05', 
            'fechavencimiento'=> '2024-04-05', 
            'razonsocial'=> 'LUIS PATRICIO VALDÉS GUTIÉRREZ', 
            'rut'=> '9728223-4', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT CALDERAS', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '21576', 
            'licitacion'=> '2182-2-LE21', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'SERVICIO DE MANTENCION PREVENTIVA Y CORRECTIVA DE MOTOBOMBAS DE TRIBUNALES DE LA JURISDICCION DE AYSÉN', 
            'fechainicio'=> '2021-07-04', 
            'fechavencimiento'=> '2024-07-04', 
            'razonsocial'=> 'LUIS PATRICIO VALDÉS GUTIÉRREZ', 
            'rut'=> '9728223-4', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT BOMBAS DE ELEVACION DE AGUA', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '21577', 
            'licitacion'=> '741484-1-LE21', 
            'tipo'=> 'Convenio precio', 
            'referencia'=> 'CONVENIO DE SERVICIO DE TRANSPORTE PARA NOTIFICACIONES DEL JUZGADO DE LETRAS DEL TRABAJO DE COYHAIQUE', 
            'fechainicio'=> '2021-06-18', 
            'fechavencimiento'=> '2024-06-18', 
            'razonsocial'=> 'DELFIN OLIVARES JARA', 
            'rut'=> '7762264-0', 
            'materia'=> 'SERVICIO DE TRANSPORTE', 
            'submateria'=> 'PASAJE DE MOVILIZACIÓN POR NOTIFICACIONES', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '22000', 
            'licitacion'=> '2182-5-LE21', 
            'tipo'=> 'Convenio precio', 
            'referencia'=> 'ARRIENDO DE EQUIPOS DISPENSADORES  Y SUMINISTRO DE AGUA PURIFICADA PARA EDIFICIOS DE TRIBUNALES DE LA JURISDICCIÓN DE AYSÉN', 
            'fechainicio'=> '2021-10-01', 
            'fechavencimiento'=> '2024-10-01', 
            'razonsocial'=> 'COMERCIALIZADORA LOS CIPRESES JOSE NAVARRO GONZALEZ EIRL', 
            'rut'=> '76618239-9', 
            'materia'=> 'ALIMENTOS Y BEBIDAS PARA PERSONAS', 
            'submateria'=> 'AGUA PURIFICADA', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '22125', 
            'licitacion'=> 'PJ22125', 
            'tipo'=> 'Orden de compra', 
            'referencia'=> 'SERVICIO TELEFONÍA MÓVIL J CHILE CHICO Y COCHRANE', 
            'fechainicio'=> '2020-04-28', 
            'fechavencimiento'=> '2030-12-31', 
            'razonsocial'=> 'ENTEL PCS TELECOMUNICACIONES SA', 
            'rut'=> '96806980-2', 
            'materia'=> 'ACCESO A INTERNET', 
            'submateria'=> 'ACCESO A INTERNET', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '22363', 
            'licitacion'=> '741465-1-CO22', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'MANTENCION DE JARDINES Y AREAS VERDES DEL JUZGADO DE LETRAS DE PUERTO AYSEN', 
            'fechainicio'=> '2022-02-16', 
            'fechavencimiento'=> '2025-02-16', 
            'razonsocial'=> 'SAVIA DEL TRANSITO HUENTEO HERRERA', 
            'rut'=> '11717210-4', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'MANTENCIÓN DE JARDINES', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '22482', 
            'licitacion'=> '2182-9-LR21', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'SERVICIO DE ASEO E INSUMOS EN UNIDADES JUDICIALES DE LA REGIÓN DE AYSÉN', 
            'fechainicio'=> '2022-03-14', 
            'fechavencimiento'=> '2024-03-14', 
            'razonsocial'=> 'COMERCIAL PANGUILEMU LTDA', 
            'rut'=> '76893640-4', 
            'materia'=> 'SERVICIO DE ASEO', 
            'submateria'=> 'SERVICIO DE ASEO DEPENDENCIAS', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '22799', 
            'licitacion'=> '2182-3-LP22', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'OBRAS DE CONSERVACION DEL EDIFICIO DE LA CORTE DE APELACIONES DE COYHAIQUE', 
            'fechainicio'=> '2022-09-08', 
            'fechavencimiento'=> '2022-11-20', 
            'razonsocial'=> 'SEBASTIAN FRANCISCO BOSSEL SOLIS', 
            'rut'=> '16831929-0', 
            'materia'=> '31 - PROGRAMAS DE INVERSION', 
            'submateria'=> 'OBRAS CIVILES - PROYECTOS', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '22943', 
            'licitacion'=> '2182-121-SE22', 
            'tipo'=> 'Orden de compra', 
            'referencia'=> 'ARRIENDO DE CASILLA DE CORREOS 2022 2023', 
            'fechainicio'=> '2022-11-18', 
            'fechavencimiento'=> '2023-11-22', 
            'razonsocial'=> 'EMPRESA DE CORREOS DE CHILE', 
            'rut'=> '60503000-9', 
            'materia'=> 'CORREO', 
            'submateria'=> 'CORREO', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '22998', 
            'licitacion'=> '2182-8-LE22', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'APRUEBA CONTRATO DE SERVICIO DE MAN PREVENTIVA DE CLIMATIZACION TRIBUNALES ZONAL COYHAIQUE', 
            'fechainicio'=> '2022-10-01', 
            'fechavencimiento'=> '2025-10-01', 
            'razonsocial'=> 'LUIS PATRICIO VALDÉS GUTIÉRREZ', 
            'rut'=> '9728223-4', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT AIRE ACONDICIONADO', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '23163', 
            'licitacion'=> '425-56-LR22', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE PRESTACIÓN DE SERVICIO DE GUARDIAS DE SEGURIDAD JURISDICCION COYHAIQUE', 
            'fechainicio'=> '2022-11-26', 
            'fechavencimiento'=> '2025-05-31', 
            'razonsocial'=> 'SERVICIOS INTEGRALES DE SEGURIDAD DE LA PATAGONIA EIRL', 
            'rut'=> '76806170-K', 
            'materia'=> 'SERVICIO DE VIGILANCIA', 
            'submateria'=> 'SERVICIO DE GUARDIAS DE SEGURIDAD', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '23220', 
            'licitacion'=> '2182-11-LE22', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE MANTENCION DE JARDINES Y AREAS VERDES PUERTO CISNES', 
            'fechainicio'=> '2023-03-13', 
            'fechavencimiento'=> '2026-03-13', 
            'razonsocial'=> 'SANDRA SOLEDAD AGUILA ROSAS', 
            'rut'=> '9348839-3', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'MANTENCIÓN DE JARDINES', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '23222', 
            'licitacion'=> '2182-12-LE22', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'APRUEBA CONTRATO POR SERVICIO DE MANTENCIÓN DE JARDINES Y ÁREAS VERDES PARA LOCALIDADES DE COYHAIQUE', 
            'fechainicio'=> '2023-02-03', 
            'fechavencimiento'=> '2026-02-03', 
            'razonsocial'=> 'ALEX DAVID MILLALONCO RIVAS', 
            'rut'=> '13969655-7', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'MANTENCIÓN DE JARDINES', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '23226', 
            'licitacion'=> '2182-1-LE23', 
            'tipo'=> 'Convenio precio', 
            'referencia'=> 'APRUEBA CONVENIO DE PRECIOS PARA EL SERVICIO DE ENCUADERNACIÓN Y EMPASTE PARA LA CORPORACIÓN ADMINISTRATIVA DEL PODER JUDICIAL ZONAL COYHAIQUE', 
            'fechainicio'=> '2023-02-03', 
            'fechavencimiento'=> '2026-01-31', 
            'razonsocial'=> 'EDUARDO ANTONIO HERNANDEZ MANSILLA', 
            'rut'=> '8258735-7', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'ENCUADERNACION', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '23320', 
            'licitacion'=> '2182-3-LE23', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'MANTENCION DE JARDINES  Y AREAS VERDES DEL JUZGADO DE LETRAS DE COCHRANE', 
            'fechainicio'=> '2023-02-22', 
            'fechavencimiento'=> '2026-02-22', 
            'razonsocial'=> 'COMERCIAL PANGUILEMU LTDA', 
            'rut'=> '76893640-4', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'MANTENCIÓN DE JARDINES', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '23321', 
            'licitacion'=> '2182-4-LE23', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'MANTENCION DE JARDINES  Y AREAS VERDES DEL JUZGADO DE LETRAS DE CHILE CHICO', 
            'fechainicio'=> '2023-03-17', 
            'fechavencimiento'=> '2026-03-17', 
            'razonsocial'=> 'COMERCIAL PANGUILEMU LTDA', 
            'rut'=> '76893640-4', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'MANTENCIÓN DE JARDINES', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '23398', 
            'licitacion'=> '2182-2-LE23', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE SERVICIO DE MANTENCIÓN PREVENTIVA Y CORRECTIVA DE CALDERAS DE CALEFACCIÓN DE TRIBUNALES DE LA JURISDICCIÓN DE AYSÉN', 
            'fechainicio'=> '2023-03-03', 
            'fechavencimiento'=> '2026-03-03', 
            'razonsocial'=> 'MARCIAL ROBERTO MORENO GATICA', 
            'rut'=> '12975530-K', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT CALDERAS', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '23422', 
            'licitacion'=> '741422-1-LE23', 
            'tipo'=> 'Convenio precio', 
            'referencia'=> 'CONVENIO DE USO PREFERENTE DE TRANSPORTE POR NOTIFICACIONES PARA EL JUZGADO DE FAMILIA DE COYHAIQUE', 
            'fechainicio'=> '2023-04-03', 
            'fechavencimiento'=> '2026-04-03', 
            'razonsocial'=> 'JULIA GLADYS MARTINEZ GARCIA', 
            'rut'=> '7672718-K', 
            'materia'=> 'SERVICIO DE TRANSPORTE', 
            'submateria'=> 'PASAJE DE MOVILIZACIÓN POR NOTIFICACIONES', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '23468', 
            'licitacion'=> '741488-1-LE23', 
            'tipo'=> 'Convenio precio', 
            'referencia'=> 'CONVENIO DE USO PREFERENTE DE TRANSPORTE POR NOTIFICACIONES PARA EL TOP COYHAIQUE', 
            'fechainicio'=> '2023-04-03', 
            'fechavencimiento'=> '2026-04-03', 
            'razonsocial'=> 'MARIA TERESA SPA', 
            'rut'=> '76945689-9', 
            'materia'=> 'SERVICIO DE TRANSPORTE', 
            'submateria'=> 'PASAJE DE MOVILIZACIÓN POR NOTIFICACIONES', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '23839', 
            'licitacion'=> '2182-7-LE23', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE PRESTACIÓN DE SERVICIO DE MANTENCION PREVENTIVA Y CORRECTIVA DE GRUPOS ELECTROGENOS DE TRIBUNALES JURISDICCION DE AYSEN', 
            'fechainicio'=> '2023-08-03', 
            'fechavencimiento'=> '2026-08-03', 
            'razonsocial'=> 'LUIS PATRICIO VALDÉS GUTIÉRREZ', 
            'rut'=> '9728223-4', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT GRUPO ELECTROGENO', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '23840', 
            'licitacion'=> '2182-6-LE23', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE PRESTACIÓN DE SERVICIO DE MANTENCION PREVENTIVA Y CORRECTIVA DE TABLEROS E INSTALACIONES ELECTRICAS DE TRIBUNALES DE AYSEN', 
            'fechainicio'=> '2023-07-21', 
            'fechavencimiento'=> '2026-07-21', 
            'razonsocial'=> 'LUIS PATRICIO VALDÉS GUTIÉRREZ', 
            'rut'=> '9728223-4', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT TABLERO ELECTRICO', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '23885', 
            'licitacion'=> '2182-8-LE23', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE SERVICIO DE MANTENCIÓN PREVENTIVA Y CORRECTIVA DE ALCANTARILLADO Y SERVICIOS HIGIENICOS TRIB DE AYSEN', 
            'fechainicio'=> '2023-07-18', 
            'fechavencimiento'=> '2026-07-18', 
            'razonsocial'=> 'SAVIA DEL TRANSITO HUENTEO HERRERA', 
            'rut'=> '11717210-4', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT DE CAMARAS ALCANTARILLADO', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '23890', 
            'licitacion'=> '2182-5-LP23', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE OBRAS DE CONSERVACION DE EDIFICIO DE LA CORTE DE APELACIONES DE COYHAIQUE', 
            'fechainicio'=> '2023-09-04', 
            'fechavencimiento'=> '2023-11-04', 
            'razonsocial'=> 'GESTION Y GERENCIA DE PROYECTOS LTDA', 
            'rut'=> '76092765-1', 
            'materia'=> '31 - PROGRAMAS DE INVERSION', 
            'submateria'=> 'OBRAS CIVILES - PROYECTOS', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '23930', 
            'licitacion'=> '2182-9-LP23', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE OBRAS DE CONSERVACION DE EDIFICIO JUZGADO DE GARANTIA DE CHILE CHICO', 
            'fechainicio'=> '2023-09-04', 
            'fechavencimiento'=> '2023-11-04', 
            'razonsocial'=> 'SEBASTIAN FRANCISCO BOSSEL SOLIS', 
            'rut'=> '16831929-0', 
            'materia'=> '31 - PROGRAMAS DE INVERSION', 
            'submateria'=> 'OBRAS CIVILES - PROYECTOS', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '23957', 
            'licitacion'=> '741256-1-LE23', 
            'tipo'=> 'Convenio precio', 
            'referencia'=> 'CONVENIO DE USO PREFERENTE DE TRANSPORTE POR NOTIFICACIONES PARA EL JUZGADO DE GTIA DE COYHAIQUE', 
            'fechainicio'=> '2023-08-21', 
            'fechavencimiento'=> '2026-08-21', 
            'razonsocial'=> 'OSCAR ANDREY MARIANTE MUÑOZ', 
            'rut'=> '11692530-3', 
            'materia'=> 'SERVICIO DE TRANSPORTE', 
            'submateria'=> 'OTROS PASAJES, FLETES, BODEGAJE', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '23960', 
            'licitacion'=> '2182-10-LE23', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE \x93SERVICIO DE MANTENCIÓN Y REPARACIÓN PREVENTIVA DE TECHUMBRES Y VENTANAS DE TRIBUNALES DE LA JURISDICCIÓN DE AYSÉN Y CONVENIO DE PRECIOS DE OBRAS MENORES PARA EDIFICIOS DE TRIBUNALES Y VIVIENDAS JUDICIALESC', 
            'fechainicio'=> '2023-09-03', 
            'fechavencimiento'=> '2026-09-03', 
            'razonsocial'=> 'SAVIA DEL TRANSITO HUENTEO HERRERA', 
            'rut'=> '11717210-4', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT TECHUMBRE /CANALETA', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '24017', 
            'licitacion'=> '2182-11-LP23', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'OBRAS DE CONSERVACION DEL EDIFICIO JUZGADO DE LETRAS Y GARANTIA DE COCHRANE', 
            'fechainicio'=> '2023-10-04', 
            'fechavencimiento'=> '2023-12-04', 
            'razonsocial'=> 'SEBASTIAN FRANCISCO BOSSEL SOLIS', 
            'rut'=> '16831929-0', 
            'materia'=> '31 - PROGRAMAS DE INVERSION', 
            'submateria'=> 'OBRAS CIVILES - PROYECTOS', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '25013', 
            'licitacion'=> '2182-15-LR23', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE PRESTACIÓN DE SERVICIOS DE ASEO E INSUMOS EN UNIDADES JUDICIALES DE LA REGÓN DE AYSEN', 
            'fechainicio'=> '2024-03-15', 
            'fechavencimiento'=> '2026-03-15', 
            'razonsocial'=> 'COM PANGUILEMU LTDA', 
            'rut'=> '76893640-4', 
            'materia'=> 'SERVICIO DE ASEO', 
            'submateria'=> 'SERVICIO DE ASEO DEPENDENCIAS', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '25147', 
            'licitacion'=> '2182-1-LE24', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE SERVICIO DE MANTENCION PREVENTIVA Y REPARATIVA DE SISTEMAS DE CALEFACCION POR TERMOACUMULADORES ELECTRICOS', 
            'fechainicio'=> '2024-04-06', 
            'fechavencimiento'=> '2027-04-06', 
            'razonsocial'=> 'Constructora EHG Limitada', 
            'rut'=> '76499318-7', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT SISTEMA DE CALEFACCIÓN', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '25259', 
            'licitacion'=> '2182-3-LE24', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE PRESTACION DE SERVICIO DE MANTENCION PREVENTIVA Y CORRECTIVA DE MOTOBOMBAS DE TRIBUNALES DE LA JURISDICCION DE AYSEN', 
            'fechainicio'=> '2024-07-05', 
            'fechavencimiento'=> '2027-07-05', 
            'razonsocial'=> 'LUIS PATRICIO VALDÉS GUTIÉRREZ', 
            'rut'=> '9728223-4', 
            'materia'=> 'MANTENIMIENTO Y REPARACION DE EDIFICACIONES', 
            'submateria'=> 'MANT BOMBAS DE ELEVACION DE AGUA', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '25260', 
            'licitacion'=> '741484-1-L124', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'Convenio de transporte preferente del Servicio de transporte para notificaciones y viajes especiales radio urbano y rural del Juzgado de Letras del Trabajo de Coyhaique', 
            'fechainicio'=> '2024-06-19', 
            'fechavencimiento'=> '2027-06-19', 
            'razonsocial'=> 'DELFÍN OLIVARES JARA', 
            'rut'=> '7762264-0', 
            'materia'=> 'SERVICIO DE TRANSPORTE', 
            'submateria'=> 'PASAJE DE MOVILIZACIÓN POR NOTIFICACIONES', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '25389', 
            'licitacion'=> '2182-7-LE24', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE OBRAS DE CONSERVACION DE EDIFICIO DEL JUZGADO DE COCHRANE', 
            'fechainicio'=> '2024-08-27', 
            'fechavencimiento'=> '2025-01-30', 
            'razonsocial'=> 'LUIS PATRICIO VALDÉS GUTIÉRREZ', 
            'rut'=> '9728223-4', 
            'materia'=> '31 - PROGRAMAS DE INVERSION', 
            'submateria'=> 'OBRAS CIVILES - PROYECTOS', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '25433', 
            'licitacion'=> '2182-14-LP24', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE SERVICIO DE OBRAS DE CONSERVACION DE EDIFICIO DEL JUZGADO DE CHILE CHICO ', 
            'fechainicio'=> '2024-10-04', 
            'fechavencimiento'=> '2025-03-18', 
            'razonsocial'=> 'LUIS PATRICIO VALDÉS GUTIÉRREZ', 
            'rut'=> '9728223-4', 
            'materia'=> '31 - PROGRAMAS DE INVERSION', 
            'submateria'=> 'OBRAS CIVILES - PROYECTOS', 
            'estado'=> 'APROBADO' 
            ],
            [
            'contrato'=> '25447', 
            'licitacion'=> '2182-17-LE24', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'CONTRATO DE ARRENDAMIENTO Y SUMIMISTRO DE AGUA PURIFICADA EN TRIBUNALES DE LA JURISDICCION', 
            'fechainicio'=> '2024-10-21', 
            'fechavencimiento'=> '2027-10-21', 
            'razonsocial'=> 'COMERCIALIZADORA LOS CIPRESES JOSE NAVARRO GONZALE', 
            'rut'=> '76618239-9', 
            'materia'=> 'ALIMENTOS Y BEBIDAS PARA PERSONAS', 
            'submateria'=> 'AGUA PURIFICADA', 
            'estado'=> 'APROBADO' 
        ],
            [
                'contrato'=> '25640', 
            'licitacion'=> '741465-1-LE24', 
            'tipo'=> 'Contrato', 
            'referencia'=> 'APRUEBA CONTRATO DE SERVICIO DE MANTENCION DE JARDINES JUZGADO DE LETRAS Y GARANTIA DE PTO AYSEN', 
            'fechainicio'=> '2025-02-17', 
            'fechavencimiento'=> '2028-02-17', 
            'razonsocial'=> 'SAVIA DEL TRÁNSITO HUENTEO HERRERA', 
            'rut'=> '11717210-4', 
            'materia'=> 'SERVICIOS GENERALES', 
            'submateria'=> 'MANTENCIÓN DE JARDINES', 
            'estado'=> 'APROBADO' 
            ],    

        ]);
    }
}