<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LicitacionesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('licitaciones')->insert([
            [
                'numero_licitacion' => '2182-10-LE21',
                'nombre' => 'SERVICIO DE MUDANZA DE BIENES Y ENSERES DE CASA',
                'descripcion' => 'SERVICIO DE MUDANZA Y TRASLADO DE MUEBLES Y ENSERES DESDE LA CIUDAD DE CAUQUENES A LA CIUDAD DE COYHAIQUE.',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 7000000.0,
                'numero_ofertas_recibidas' => 4,
                'fecha_publicacion' => '2021-11-22 13:14:00',
                'fecha_adjudicacion' => '2021-12-07 12:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-10-LE23',
                'nombre' => 'CONTRATO DE MANTENCIÓN DE TECHUMBRES',
                'descripcion' => 'PAC(3177-2-PC23) MANTENCIÓN Y REPARACIÓN PREVENTIVA DE TECHUMBRES Y VENTANAS DE TRIBUNALES DE LA JURISDICCIÓN DE AYSEN y CONVENIO DE PRECIOS DE OBRAS MENORES PARA EDIFICIOS DE TRIBUNALES Y VIVIENDAS JUDICIALES',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 462.0,
                'numero_ofertas_recibidas' => 5,
                'fecha_publicacion' => '2023-05-30 12:58:00',
                'fecha_adjudicacion' => '2023-07-31 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-10-LE24',
                'nombre' => 'HABILITACIÓN DE EDIFICIO COYHAIQUE',
                'descripcion' => 'HABILITACIÓN OFICINA DE LIQUIDACIÓN PARA EL PODER JUDICIAL',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 40000000.0,
                'numero_ofertas_recibidas' => 1,
                'fecha_publicacion' => '2024-06-21 15:52:00',
                'fecha_adjudicacion' => '2024-10-02 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-11-LE22',
                'nombre' => 'SERVICIO DE JARDINERIA',
                'descripcion' => 'SERVICIO DE JARDINERIA PARA EL JUZGASO DE LETRAS DE PUERTO CISNES',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 5.0,
                'numero_ofertas_recibidas' => 1,
                'fecha_publicacion' => '2022-12-29 12:04:00',
                'fecha_adjudicacion' => '2023-02-10 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-11-LP23',
                'nombre' => 'OBRAS DE CONSERVACIÓN DE EDIFICIO',
                'descripcion' => 'OBRAS DE CONSERVACIÓN EDIFICIO DEL JUZGADO DE LETRAS DE COCHRANE',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 85085000.0,
                'numero_ofertas_recibidas' => 4,
                'fecha_publicacion' => '2023-06-30 11:24:00',
                'fecha_adjudicacion' => '2023-09-29 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-11-LP24',
                'nombre' => 'OBRAS PREVIAS DE CONSTRUCCIÓN',
                'descripcion' => 'OBRAS PRELIMINARES DE CONSTRUCCION DEL EDIFICIO DEL JUZGADO DE LETRAS Y GARANTIA DE PUERTO AYSEN',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 89998000.0,
                'numero_ofertas_recibidas' => 2,
                'fecha_publicacion' => '2024-07-12 13:10:00',
                'fecha_adjudicacion' => '2024-09-04 15:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-12-LE22',
                'nombre' => 'SERVICIO DE JARDINERIA',
                'descripcion' => 'SERVICIO DE JARDINERIA TRIBUNALES DE LA CIUDAD DE COYHAIQUE',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 22.0,
                'numero_ofertas_recibidas' => 4,
                'fecha_publicacion' => '2022-12-30 12:08:00',
                'fecha_adjudicacion' => '2023-02-09 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-12-LE24',
                'nombre' => 'Mudanza y Traslado de Muebles y Enseres',
                'descripcion' => 'Mudanza y Traslado de Muebles y Enseres desde Antofagasta a Coyhaique',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 10000000.0,
                'numero_ofertas_recibidas' => 5,
                'fecha_publicacion' => '2024-07-24 13:30:00',
                'fecha_adjudicacion' => '2024-08-19 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-13-L124',
                'nombre' => 'COMPRA DE PETROLEO',
                'descripcion' => 'Adquisición de 5.000 litros de combustible para estanque de petrolero del Juzgado de letras de Puerto Cisnes.',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 6466000.0,
                'numero_ofertas_recibidas' => 1,
                'fecha_publicacion' => '2024-08-02 10:14:00',
                'fecha_adjudicacion' => '2024-08-20 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-13-LE23',
                'nombre' => 'REPARACION DE VIVIENDA',
                'descripcion' => 'REPARACIÓN DE VIVIENDA JUDICIAL EN LA CIUDAD DE COYHAIQUE.',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 13200000.0,
                'numero_ofertas_recibidas' => 5,
                'fecha_publicacion' => '2023-08-03 12:42:00',
                'fecha_adjudicacion' => '2023-10-03 16:15:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-14-LE23',
                'nombre' => 'MUDANZA Y TRASLADO DE MUEBLES Y ENSERES',
                'descripcion' => '02 MUDANZAS Y TRASLADOS DE MUEBLES Y ENSERES A LA REGION DE AYSEN.',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 10000000.0,
                'numero_ofertas_recibidas' => 7,
                'fecha_publicacion' => '2023-08-30 12:04:00',
                'fecha_adjudicacion' => '2023-09-13 17:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-14-LP24',
                'nombre' => 'OBRAS DE CONSERVACIÓN DE EDIFICIO',
                'descripcion' => 'OBRAS DE CONSERVACIÓN DE EDIFICIO DEL JUZGADO DE LETRAS DE CHILE CHICO',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 77350000.0,
                'numero_ofertas_recibidas' => 1,
                'fecha_publicacion' => '2024-08-08 11:55:00',
                'fecha_adjudicacion' => '2024-09-23 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-15-L124',
                'nombre' => 'Obras interiores Juzgado de Letras de Cochrane',
                'descripcion' => 'En general los trabajos consisten en: 1.Desarme de Puerta existente. 2.Tapeo de Vano de puerta 3.Suministro e instalación de tabique vidriado 4.Puerta de tabique vidriado.',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 4500000.0,
                'numero_ofertas_recibidas' => 1,
                'fecha_publicacion' => '2024-08-30 15:10:00',
                'fecha_adjudicacion' => '2024-09-13 17:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-15-LR23',
                'nombre' => 'SERVICIO DE ASEO EDIFICIOS',
                'descripcion' => 'SERVICIO DE ASEO E INSUMOS EN UNIDADES JUDICIALES DE LA REGIÓN DE AYSÉN',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 817.0,
                'numero_ofertas_recibidas' => 3,
                'fecha_publicacion' => '2023-11-06 16:26:00',
                'fecha_adjudicacion' => '2024-01-17 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-16-LE23',
                'nombre' => 'Mudanza y Traslado de Muebles y Enseres',
                'descripcion' => 'Mudanza y Traslado de Muebles y Enseres Chillan - Coyhaique',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 7000000.0,
                'numero_ofertas_recibidas' => 2,
                'fecha_publicacion' => '2023-12-13 12:44:00',
                'fecha_adjudicacion' => '2024-01-02 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-17-LE24',
                'nombre' => 'ARRIENDO DE DISPENSADORES Y SUMINISTRO DE AGUA',
                'descripcion' => 'ARRIENDO DE EQUIPOS DISPENSADORES Y SUMINISTRO DE AGUA PURIFICADA PARA EDIFICIOS DE TRIBUNALES DE LA JURISDICCIÓN DE AYSÉN',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 8000000.0,
                'numero_ofertas_recibidas' => 2,
                'fecha_publicacion' => '2024-09-27 10:11:00',
                'fecha_adjudicacion' => '2024-10-11 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-18-LE24',
                'nombre' => 'OBRAS DE CONSERVACIÓN DE EDIFICIO',
                'descripcion' => 'OBRAS DE CONSERVACIÓN EDIFICIO DE LA CORTE DE APELACIONES DE COYHAIQUE',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 40000000.0,
                'numero_ofertas_recibidas' => 2,
                'fecha_publicacion' => '2024-09-27 15:33:00',
                'fecha_adjudicacion' => '2024-11-08 19:54:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-1-LE21',
                'nombre' => 'MANTENCIÓN DE TERMOACUMULADORES',
                'descripcion' => 'PAC(2182-2-PC21) SERVICIO DE MANTENCION DE TERMOACUMULADORES DE CALEFACCION DE EDIFICIOS DE TRIBUNALES DE LA JURIDICCION DE COYHAIQUE',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 169.0,
                'numero_ofertas_recibidas' => 3,
                'fecha_publicacion' => '2021-02-24 14:39:00',
                'fecha_adjudicacion' => '2021-03-24 15:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-1-LE22',
                'nombre' => 'SERVICIO DE MUDANZA',
                'descripcion' => 'MUDANZA Y TRASLADO DE MUEBLES Y ENSERES DESDE LA CIUDAD DE PUERTO AYSEN A LA CIUDAD DE COYHAIQUE',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 4500000.0,
                'numero_ofertas_recibidas' => 3,
                'fecha_publicacion' => '2022-02-08 12:44:00',
                'fecha_adjudicacion' => '2022-02-23 15:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-1-LE23',
                'nombre' => 'ENCUADERNACION Y EMPASTE PARA EL PODER JUDICIAL',
                'descripcion' => 'CONVENIO DE PRECIOS SERVICIO DE ENCUADERNACION Y EMPASTE PARA EL PODER JUDICIAL ZONAL COYHAIQUE',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 6200000.0,
                'numero_ofertas_recibidas' => 2,
                'fecha_publicacion' => '2023-01-04 13:04:00',
                'fecha_adjudicacion' => '2023-02-16 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-1-LE24',
                'nombre' => 'MANTENCIÓN TERMO ACUMULADORES',
                'descripcion' => 'PAC(3177-1-PC24) SERVICIO DE MANTENCIÓN PREVENTIVA Y REPARATIVA DE SISTEMA DE CALEFACCION POR TERMO ACUMULADORES ELECTRICOS PARA TRIBUNALES DE LA JURISDICCION DE AYSEN',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 166.0,
                'numero_ofertas_recibidas' => 1,
                'fecha_publicacion' => '2024-01-24 15:53:00',
                'fecha_adjudicacion' => '2024-03-18 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-2-LE21',
                'nombre' => 'MANTENCIÓN MOTOBOMBAS',
                'descripcion' => 'PAC (2182-3-PC21) SERVICIO DE MANTENCION PREVENTIVA Y CORRECTIVA DE MOTOBOMBAS DE TRIBUNALES DE LA JURISDICCION DE AYSÉN',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 183.0,
                'numero_ofertas_recibidas' => 1,
                'fecha_publicacion' => '2021-04-09 12:45:00',
                'fecha_adjudicacion' => '2021-05-20 17:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-2-LE22',
                'nombre' => 'SERVICIO DE MUDANZA',
                'descripcion' => 'SERVICIO DE MUDANZA COYHAIQUE-AYSEN PARA FUNCIONARIO DEL PODER JUDICIAL',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 4500000.0,
                'numero_ofertas_recibidas' => 3,
                'fecha_publicacion' => '2022-03-04 13:46:00',
                'fecha_adjudicacion' => '2022-03-29 12:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-2-LE23',
                'nombre' => 'MANTENCIÓN DE CALDERAS',
                'descripcion' => 'SERVICIO DE MANTENCION PREVENTIVA Y CORRECTIVA DE CALDERAS DE CALEFACCIÓN DE TRIBUNALES DE LA JURISDICCION DE AYSÉN',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 168.0,
                'numero_ofertas_recibidas' => 3,
                'fecha_publicacion' => '2023-01-16 12:16:00',
                'fecha_adjudicacion' => '2023-02-27 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-2-LE24',
                'nombre' => 'Servicio de mudanza',
                'descripcion' => 'Mudanza y Traslado de Muebles y Enseres Santiago-Coyhaique.',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 7000000.0,
                'numero_ofertas_recibidas' => 4,
                'fecha_publicacion' => '2024-03-13 11:11:00',
                'fecha_adjudicacion' => '2024-04-01 15:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-3-LE23',
                'nombre' => 'SERVICIO DE JARDINERIA',
                'descripcion' => 'SERVICIO DE JARDINERIA DE JUZGADO DE LETRAS DE COCHRANE',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 4.8,
                'numero_ofertas_recibidas' => 3,
                'fecha_publicacion' => '2023-01-23 12:50:00',
                'fecha_adjudicacion' => '2023-03-08 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-3-LE24',
                'nombre' => 'MANTENCION DE MOTOBOMBAS',
                'descripcion' => 'SERVICIO DE MANTENCION PREVENTIVA Y CORRECTIVA DE MOTOBOMBAS DE TRIBUNALES DE LA JURISDICCION DE AYSEN',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 549.0,
                'numero_ofertas_recibidas' => 3,
                'fecha_publicacion' => '2024-03-26 15:52:00',
                'fecha_adjudicacion' => '2024-05-08 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-3-R122',
                'nombre' => 'OBRAS DE CONSERVACIÓN DE EDIFICIO.',
                'descripcion' => 'OBRAS DE CONSERVACIÓN DE EDIFICIO DE LA CORTE DE APELACIONES DE COYHAIQUE',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 68000000.0,
                'numero_ofertas_recibidas' => 3,
                'fecha_publicacion' => '2022-04-29 14:39:00',
                'fecha_adjudicacion' => '2022-07-28 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-4-LE21',
                'nombre' => 'ADQUISICION DE TONER',
                'descripcion' => 'ADQUISICIÓN DE INSUMOS COMPUTACIONES PARA LA ADMINISTRACIÓN ZONAL DE COYHAIQUE',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 18000.0,
                'numero_ofertas_recibidas' => 3,
                'fecha_publicacion' => '2021-08-05 14:43:00',
                'fecha_adjudicacion' => '2021-09-15 14:20:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-4-LE22',
                'nombre' => 'SERVICIO DE MURANZA',
                'descripcion' => 'MURANZA DE BIENES DESDE LA CIUDAD DE VALDIVIA A LA CIUDAD DE CHILE CHICO',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 6000000.0,
                'numero_ofertas_recibidas' => 3,
                'fecha_publicacion' => '2022-05-31 12:31:00',
                'fecha_adjudicacion' => '2022-06-14 14:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-4-LE23',
                'nombre' => 'SERVICIO DE JARDINERIA',
                'descripcion' => 'SERVICIO DE JARDINERIA DE JUZGADO DE LETRAS DE CHILE CHICO.',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 4.8,
                'numero_ofertas_recibidas' => 2,
                'fecha_publicacion' => '2023-01-23 12:49:00',
                'fecha_adjudicacion' => '2023-03-08 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-5-LE21',
                'nombre' => 'ARRIENDO DE EQUIPO Y SUMINISTRO DE AGUA PURIFICADA',
                'descripcion' => 'ARRIENDO DE EQUIPOS DISPENSADORES Y SUMINISTRO DE AGUA PURIFICADA PARA EDIFICIOS DE TRIBUNALES DE LA JURISDICCIÓN DE AYSÉN',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 360.0,
                'numero_ofertas_recibidas' => 1,
                'fecha_publicacion' => '2021-08-17 13:35:00',
                'fecha_adjudicacion' => '2021-09-29 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-5-LE22',
                'nombre' => 'REPARACIÓN DE VIVIENDAS',
                'descripcion' => 'REPARACIÓN DE VIVIENDAS JUDICIALES DE LA LOCALIDAD DE PUERTO CISNES',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 12150000.0,
                'numero_ofertas_recibidas' => 1,
                'fecha_publicacion' => '2022-06-07 11:58:00',
                'fecha_adjudicacion' => '2022-07-11 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-5-LP23',
                'nombre' => 'OBRAS DE CONSERVACIÓN DE EDIFICIO',
                'descripcion' => 'OBRAS DE CONSERVACIÓN DE EDIFICIO DE LA CORTE DE APELACIONES DE COYHAIQUE, SUMINISTRO E INSTALACIÓN DE VENTANAS TERMOPANEL.',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 86632000.0,
                'numero_ofertas_recibidas' => 5,
                'fecha_publicacion' => '2023-03-30 11:52:00',
                'fecha_adjudicacion' => '2023-06-30 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-6-L124',
                'nombre' => 'MUDANZA',
                'descripcion' => 'MUDANZA Y TRASLADO DE MUEBLES Y ENSERES DESDE COYHAIQUE A CHILE CHICO',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 4000000.0,
                'numero_ofertas_recibidas' => 2,
                'fecha_publicacion' => '2024-04-19 12:38:00',
                'fecha_adjudicacion' => '2024-07-01 10:15:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-6-LE21',
                'nombre' => 'CIERRE PERIMETRAL TERRENO PODER JUDICIAL',
                'descripcion' => 'CIERRE PERIMETRAL TERRENO PODER JUDICIAL MEDIANTE MALLA ACMAFOR 3D O EQUIVALENTE.',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 35000000.0,
                'numero_ofertas_recibidas' => 3,
                'fecha_publicacion' => '2021-08-26 11:46:00',
                'fecha_adjudicacion' => '2021-09-24 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-6-LE23',
                'nombre' => 'SERVICIO DE MANTENCION PREVENTIVA Y CORRECTIVA DE TABLEROS E INSTALACIONES ELECTRICAS',
                'descripcion' => 'SERVICIO DE MANTENCION PREVENTIVA Y CORRECTIVA DE TABLEROS E INSTALACIONES ELECTRICAS DE EDIFICIOS DE TRIBUNALES DE LA REGIÓN DE AYSEN.',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 94.0,
                'numero_ofertas_recibidas' => 4,
                'fecha_publicacion' => '2023-04-17 13:12:00',
                'fecha_adjudicacion' => '2023-06-30 13:11:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-7-LE21',
                'nombre' => 'REPARACIÓN DE VIVIENDA',
                'descripcion' => 'REPARACIÓN Y/O MANTENCIÓN DE VIVIENDA JUDICIAL',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 12000000.0,
                'numero_ofertas_recibidas' => 3,
                'fecha_publicacion' => '2021-10-08 13:22:00',
                'fecha_adjudicacion' => '2021-11-08 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-7-LE22',
                'nombre' => 'MUDANZA Y TRASLADO DE MUEBLES Y ENSERES PARA EL PODER JUDICIAL COYHAIQUE',
                'descripcion' => 'MUDANZA Y TRASLADO DE MUEBLES Y ENSERES DESDE LA CIUDAD DE COCHRANE A LA CIUDAD DE COYHAIQUE',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 6000000.0,
                'numero_ofertas_recibidas' => 3,
                'fecha_publicacion' => '2022-08-02 12:09:00',
                'fecha_adjudicacion' => '2022-08-25 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-7-LE23',
                'nombre' => 'SERVICIO DE MANTENCION DE GRUPOS ELECTROGENOS TRIBUNALES REGIÓN DE AYSEN',
                'descripcion' => '(PAC)3177-3-PC23 SERVICIO DE MANTENCION DE GRUPOS ELECTROGENOS TRIBUNALES REGIÓN DE AYSEN',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 406.0,
                'numero_ofertas_recibidas' => 5,
                'fecha_publicacion' => '2023-04-17 13:12:00',
                'fecha_adjudicacion' => '2023-06-30 13:12:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-7-LE24',
                'nombre' => 'OBRAS DE CONSERVACIÓN DE EDIFICIO',
                'descripcion' => 'OBRAS DE CONSERVACIÓN EDIFICIO DEL JUZGADO DE LETRAS DE COCHRANE',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 64300000.0,
                'numero_ofertas_recibidas' => 5,
                'fecha_publicacion' => '2024-04-30 11:24:00',
                'fecha_adjudicacion' => '2024-07-29 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-8-L124',
                'nombre' => 'COMPRA DE PETROLEO',
                'descripcion' => 'COMPRA DE PETROLEO PARA CALDERA DE CALEFACCIÓN DEL JUZGADO DE LETRAS DE COCHRANE..',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 6466000.0,
                'numero_ofertas_recibidas' => 1,
                'fecha_publicacion' => '2024-05-10 10:20:00',
                'fecha_adjudicacion' => '2024-05-17 13:28:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-8-LE21',
                'nombre' => 'REPARACIÓN DE VIVIENDA',
                'descripcion' => 'MANTENCIÓN Y/O REPARACIÓN DE VIVIENDA JUDICIAL',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 6000000.0,
                'numero_ofertas_recibidas' => 4,
                'fecha_publicacion' => '2021-10-18 13:46:00',
                'fecha_adjudicacion' => '2021-11-15 15:30:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-8-LE22',
                'nombre' => 'MANTENIMIENTO DE EQUIPOS EEAA',
                'descripcion' => 'SERVICIO DE MANTENCION PREVENTIVA Y CORRECTIVA DE EQUIPOS DE CLIMATIZACION DE TRIBUNALES DE LA JURISDICCION DE AYSEN',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 331.0,
                'numero_ofertas_recibidas' => 4,
                'fecha_publicacion' => '2022-08-24 13:11:00',
                'fecha_adjudicacion' => '2022-10-24 15:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-8-LE23',
                'nombre' => 'SERVICIO DE MANTENCION PREVENTIVA Y CORRECTIVA DE ALCANTARILLADO Y SERVICIOS HIGIENICOS',
                'descripcion' => 'SERVICIO DE MANTENCION PREVENTIVA Y CORRECTIVA DE ALCANTARILLADO Y SERVICIOS HIGIENICOS DE TRIBUNALES DE LA JURISDICCIÓN DE AYSEN',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 188.0,
                'numero_ofertas_recibidas' => 2,
                'fecha_publicacion' => '2023-04-17 13:11:00',
                'fecha_adjudicacion' => '2023-06-30 13:12:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-9-LE24',
                'nombre' => 'REPARACION DE VIVIENDA',
                'descripcion' => 'OBRAS DE REPARACIÓN VIVIENDA JUDICIAL UBICADA EN LA LOCALIDAD DE PUERTO CISNES.',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 13300000.0,
                'numero_ofertas_recibidas' => 4,
                'fecha_publicacion' => '2024-05-10 12:49:00',
                'fecha_adjudicacion' => '2024-06-19 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-9-LP23',
                'nombre' => 'OBRAS DE CONSERVACIÓN DE EDIFICIO',
                'descripcion' => 'OBRAS DE CONSERVACIÓN EDIFICIO DEL JUZGADO DE LETRAS DE CHILE CHICO',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 85085000.0,
                'numero_ofertas_recibidas' => 5,
                'fecha_publicacion' => '2023-04-28 10:54:00',
                'fecha_adjudicacion' => '2023-07-24 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
            [
                'numero_licitacion' => '2182-9-LR21',
                'nombre' => 'SERVICIO DE ASEO DE EDIFICIOS',
                'descripcion' => 'SERVICIO DE ASEO E INSUMOS EN UNIDADES JUDICIALES DE LA REGIÓN DE AYSEN',
                'estado' => 'Adjudicada',
                'tipo' => 'Pública',
                'unidad_compra' => 'Corp. Adm. del Poder Judicial - Coyhaique',
                'monto_total_estimado' => 583.0,
                'numero_ofertas_recibidas' => 2,
                'fecha_publicacion' => '2021-11-09 11:22:00',
                'fecha_adjudicacion' => '2022-01-19 16:00:00',
                'created_at' => '2025-04-08 14:49:47',
                'updated_at' => '2025-04-08 14:49:47',
            ],
        ]);
    }
}
